data = [
  {
    "Year": 1896,
    "MGResult": 29.15,
    "MGCountry": "USA",
    "MGAthlete": "Bob Garrett",
    "WGResult": 0,
    "WGCountry": 0,
    "WGAthlete": 0,
    "MSResult": 28.95,
    "MSCountry": "Greece",
    "MSAthlete": "Panayiotis Paraskevopoulos",
    "WSResult": 0,
    "WSCountry": 0,
    "WSAthlete": 0,
    "MBResult": 28.78,
    "MBCountry": "Greece",
    "MBAthlete": "Sotiris Versis",
    "WBResult": 0,
    "WBCountry": 0,
    "WBAthlete": 0
  },
  {
    "Year": 1900,
    "MGResult": 36.04,
    "MGCountry": "Hungary",
    "MGAthlete": "Rudolf Bauer",
    "WGResult": 0,
    "WGCountry": 0,
    "WGAthlete": 0,
    "MSResult": 35.25,
    "MSCountry": "Bohema",
    "MSAthlete": "Frantisek Janda-Suk",
    "WSResult": 0,
    "WSCountry": 0,
    "WSAthlete": 0,
    "MBResult": 34.6,
    "MBCountry": "USA",
    "MBAthlete": "Richard Sheldon",
    "WBResult": 0,
    "WBCountry": 0,
    "WBAthlete": 0
  },
  {
    "Year": 1904,
    "MGResult": 39.28,
    "MGCountry": "USA",
    "MGAthlete": "Martin Sheridan",
    "WGResult": 0,
    "WGCountry": 0,
    "WGAthlete": 0,
    "MSResult": 39.28,
    "MSCountry": "USA",
    "MSAthlete": "Ralph Rose",
    "WSResult": 0,
    "WSCountry": 0,
    "WSAthlete": 0,
    "MBResult": 37.68,
    "MBCountry": "Greece",
    "MBAthlete": "Nicolaos Georgantas",
    "WBResult": 0,
    "WBCountry": 0,
    "WBAthlete": 0
  },
  {
    "Year": 1908,
    "MGResult": 40.89,
    "MGCountry": "USA",
    "MGAthlete": "Martin Sheridan",
    "WGResult": 0,
    "WGCountry": 0,
    "WGAthlete": 0,
    "MSResult": 40.7,
    "MSCountry": "USA",
    "MSAthlete": "Merritt Giffin",
    "WSResult": 0,
    "WSCountry": 0,
    "WSAthlete": 0,
    "MBResult": 39.44,
    "MBCountry": "USA",
    "MBAthlete": "Bill Horr",
    "WBResult": 0,
    "WBCountry": 0,
    "WBAthlete": 0
  },
  {
    "Year": 1912,
    "MGResult": 45.21,
    "MGCountry": "Finland",
    "MGAthlete": "Armas Taipale",
    "WGResult": 0,
    "WGCountry": 0,
    "WGAthlete": 0,
    "MSResult": 42.32,
    "MSCountry": "USA",
    "MSAthlete": "Leslie Byrd",
    "WSResult": 0,
    "WSCountry": 0,
    "WSAthlete": 0,
    "MBResult": 42.28,
    "MBCountry": "USA",
    "MBAthlete": "James Duncan",
    "WBResult": 0,
    "WBCountry": 0,
    "WBAthlete": 0
  },
    {
        //No Olympics
    "Year": 1916,
    "MGResult": 44.94,
    "MGCountry": 0,
    "MGAthlete": 0,
    "WGResult": 0,
    "WGCountry": 0,
    "WGAthlete": 0,
    "MSResult": 43.255,
    "MSCountry": 0,
    "MSAthlete": 0,
    "WSResult": 0,
    "WSCountry": 0,
    "WSAthlete": 0,
    "MBResult": 42.205,
    "MBCountry": 0,
    "MBAthlete": 0,
    "WBResult": 0,
    "WBCountry": 0,
    "WBAthlete": 0
  },
  {
    "Year": 1920,
    "MGResult": 44.68,
    "MGCountry": "Finland",
    "MGAthlete": "Elmer Niklander",
    "WGResult": 0,
    "WGCountry": 0,
    "WGAthlete": 0,
    "MSResult": 44.19,
    "MSCountry": "Finland",
    "MSAthlete": "Armas Taipale",
    "WSResult": 0,
    "WSCountry": 0,
    "WSAthlete": 0,
    "MBResult": 42.13,
    "MBCountry": "USA",
    "MBAthlete": "August Pope",
    "WBResult": 0,
    "WBCountry": 0,
    "WBAthlete": 0
  },
  {
    "Year": 1924,
    "MGResult": 46.15,
    "MGCountry": "USA",
    "MGAthlete": "Bud Houser",
    "WGResult": 0,
    "WGCountry": 0,
    "WGAthlete": 0,
    "MSResult": 44.95,
    "MSCountry": "Finland",
    "MSAthlete": "Vilho Niittymaa",
    "WSResult": 0,
    "WSCountry": 0,
    "WSAthlete": 0,
    "MBResult": 44.83,
    "MBCountry": "USA",
    "MBAthlete": "Thomas Lieb",
    "WBResult": 0,
    "WBCountry": 0,
    "WBAthlete": 0
  },
  {
    "Year": 1928,
    "MGResult": 47.32,
    "MGCountry": "USA",
    "MGAthlete": "Bud Houser",
    "WGResult": 39.62,
    "WGCountry": "Poland",
    "WGAthlete": "Halina Konopacka",
    "MSResult": 47.23,
    "MSCountry": "Finland",
    "MSAthlete": "Antero Kivi",
    "WSResult": 37.08,
    "WSCountry": "USA",
    "WSAthlete": "Lillian Copeland",
    "MBResult": 47.1,
    "MBCountry": "USA",
    "MBAthlete": "James Corson",
    "WBResult": 35.92,
    "WBCountry": "Sweden",
    "WBAthlete": "Ruth Svedberg"
  },
  {
    "Year": 1932,
    "MGResult": 49.49,
    "MGCountry": "USA",
    "MGAthlete": "John Anderson",
    "WGResult": 40.58,
    "WGCountry": "USA",
    "WGAthlete": "Lillian Copeland",
    "MSResult": 48.47,
    "MSCountry": "USA",
    "MSAthlete": "Henry LaBorde",
    "WSResult": 40.12,
    "WSCountry": "USA",
    "WSAthlete": "Ruth Osborn",
    "MBResult": 47.85,
    "MBCountry": "France",
    "MBAthlete": "Paul Winter",
    "WBResult": 38.74,
    "WBCountry": "Poland",
    "WBAthlete": "Jadwiga Wajs"
  },
  {
    "Year": 1936,
    "MGResult": 50.48,
    "MGCountry": "USA",
    "MGAthlete": "Ken Carpenter",
    "WGResult": 47.63,
    "WGCountry": "Germany",
    "WGAthlete": "Gisela Mauermayer",
    "MSResult": 49.36,
    "MSCountry": "USA",
    "MSAthlete": "Gordon Dunn",
    "WSResult": 46.22,
    "WSCountry": "Poland",
    "WSAthlete": "Jadwiga Wajs",
    "MBResult": 49.23,
    "MBCountry": "Italy",
    "MBAthlete": "Giorgio Oberweger",
    "WBResult": 39.8,
    "WBCountry": "Germany",
    "WBAthlete": "Paula Mollenhauer"
  },
    {
        //No Olympics
    "Year": 1940,
    "MGResult": 51.25,
    "MGCountry": 0,
    "MGAthlete": 0,
    "WGResult": 45.73,
    "WGCountry": 0,
    "WGAthlete": 0,
    "MSResult": 50.17,
    "MSCountry": 0,
    "MSAthlete": 0,
    "WSResult": 44.54,
    "WSCountry": 0,
    "WSAthlete": 0,
    "MBResult": 49.75,
    "MBCountry": 0,
    "MBAthlete": 0,
    "WBResult": 40.03,
    "WBCountry": 0,
    "WBAthlete": 0
  },
    {
        //No Olympics
    "Year": 1944,
    "MGResult": 52.01,
    "MGCountry": 0,
    "MGAthlete": 0,
    "WGResult": 43.83,
    "WGCountry": 0,
    "WGAthlete": 0,
    "MSResult": 50.97,
    "MSCountry": 0,
    "MSAthlete": 0,
    "WSResult": 42.86,
    "WSCountry": 0,
    "WSAthlete": 0,
    "MBResult": 50.26,
    "MBCountry": 0,
    "MBAthlete": 0,
    "WBResult": 40.25,
    "WBCountry": 0,
    "WBAthlete": 0
  },
  {
    "Year": 1948,
    "MGResult": 52.78,
    "MGCountry": "Italy",
    "MGAthlete": "Adolfo Consolini",
    "WGResult": 41.92,
    "WGCountry": "France",
    "WGAthlete": "Micheline Ostermeyer",
    "MSResult": 51.78,
    "MSCountry": "Italy",
    "MSAthlete": "Giuseppe Tosi",
    "WSResult": 41.17,
    "WSCountry": "Italy",
    "WSAthlete": "Edera Gentile-Cordiale",
    "MBResult": 50.77,
    "MBCountry": "USA",
    "MBAthlete": "Fortune Gordien",
    "WBResult": 40.47,
    "WBCountry": "France",
    "WBAthlete": "Jacqueline Mazeas"
  },
  {
    "Year": 1952,
    "MGResult": 55.03,
    "MGCountry": "USA",
    "MGAthlete": "Sim Iness",
    "WGResult": 51.42,
    "WGCountry": "USSR",
    "WGAthlete": "Nina Ponomareva",
    "MSResult": 53.78,
    "MSCountry": "Italy",
    "MSAthlete": "Adolfo Consolini",
    "WSResult": 47.08,
    "WSCountry": "USSR",
    "WSAthlete": "Yelizaveta Bagryantseva",
    "MBResult": 53.28,
    "MBCountry": "USA",
    "MBAthlete": "James Dillion",
    "WBResult": 46.29,
    "WBCountry": "USSR",
    "WBAthlete": "Nina Dumbadze"
  },
  {
    "Year": 1956,
    "MGResult": 56.36,
    "MGCountry": "USA",
    "MGAthlete": "Al Oerter",
    "WGResult": 53.69,
    "WGCountry": "Czechoslovakia",
    "WGAthlete": "Olga Fikotova",
    "MSResult": 54.81,
    "MSCountry": "USA",
    "MSAthlete": "Fortune Gordien",
    "WSResult": 52.24,
    "WSCountry": "USSR",
    "WSAthlete": "Irina Beglyakova",
    "MBResult": 54.4,
    "MBCountry": "USA",
    "MBAthlete": "Des Koch",
    "WBResult": 52.02,
    "WBCountry": "USSR",
    "WBAthlete": "Nina Ponomareva"
  },
  {
    "Year": 1960,
    "MGResult": 59.18,
    "MGCountry": "USA",
    "MGAthlete": "Al Oerter",
    "WGResult": 55.1,
    "WGCountry": "USSR",
    "WGAthlete": "Nina Ponomareva",
    "MSResult": 58.02,
    "MSCountry": "USA",
    "MSAthlete": "Rink Babka",
    "WSResult": 52.59,
    "WSCountry": "USSR",
    "WSAthlete": "Tamara Press",
    "MBResult": 57.16,
    "MBCountry": "USA",
    "MBAthlete": "Richard Cochran",
    "WBResult": 52.36,
    "WBCountry": "Romania",
    "WBAthlete": "Lia Manoliu"
  },
  {
    "Year": 1964,
    "MGResult": 61,
    "MGCountry": "USA",
    "MGAthlete": "Al Oerter",
    "WGResult": 57.27,
    "WGCountry": "USSR",
    "WGAthlete": "Tamara Press",
    "MSResult": 60.52,
    "MSCountry": "Czechoslovakia",
    "MSAthlete": "Ludvik Danek",
    "WSResult": 57.21,
    "WSCountry": "Germany",
    "WSAthlete": "Ingrid Lotz",
    "MBResult": 59.49,
    "MBCountry": "USA",
    "MBAthlete": "David Weill",
    "WBResult": 56.97,
    "WBCountry": "Romania",
    "WBAthlete": "Lia Manoliu"
  },
  {
    "Year": 1968,
    "MGResult": 64.78,
    "MGCountry": "USA",
    "MGAthlete": "Al Oerter",
    "WGResult": 58.28,
    "WGCountry": "Romania",
    "WGAthlete": "Lia Manoliu",
    "MSResult": 63.08,
    "MSCountry": "East Germany",
    "MSAthlete": "Lothar Milde",
    "WSResult": 57.76,
    "WSCountry": "West Germany",
    "WSAthlete": "Liesel Westermann",
    "MBResult": 62.92,
    "MBCountry": "Czechoslovakia",
    "MBAthlete": "Ludvik Danek",
    "WBResult": 54.9,
    "WBCountry": "Hungary",
    "WBAthlete": "Jolan Kleiber"
  },
  {
    "Year": 1972,
    "MGResult": 64.4,
    "MGCountry": "Czechoslovakia",
    "MGAthlete": "Ludvik Danek",
    "WGResult": 66.62,
    "WGCountry": "USSR",
    "WGAthlete": "Faina Melnik",
    "MSResult": 63.5,
    "MSCountry": "USA",
    "MSAthlete": "Jay Silvester",
    "WSResult": 54.9,
    "WSCountry": "Romania",
    "WSAthlete": "Argentina Menis",
    "MBResult": 63.4,
    "MBCountry": "Sweden",
    "MBAthlete": "Rickard Bruch",
    "WBResult": 64.34,
    "WBCountry": "Bulgaria",
    "WBAthlete": "Vasilka Stoeva"
  },
  {
    "Year": 1976,
    "MGResult": 67.5,
    "MGCountry": "USA",
    "MGAthlete": "Mac Wilkins",
    "WGResult": 69,
    "WGCountry": "East Germany",
    "WGAthlete": "Evelin Jahl-Schlaak",
    "MSResult": 66.22,
    "MSCountry": "East Germany",
    "MSAthlete": "Wolfgang Schmidt",
    "WSResult": 66.62,
    "WSCountry": "Bulgaria",
    "WSAthlete": "Maria Petkova-Vergova",
    "MBResult": 65.7,
    "MBCountry": "USA",
    "MBAthlete": "John Powell",
    "WBResult": 66.84,
    "WBCountry": "East Germany",
    "WBAthlete": "Gabriele Hinzmann"
  },
  {
    "Year": 1980,
    "MGResult": 66.64,
    "MGCountry": "USSR",
    "MGAthlete": "Viktor Rashchupkin",
    "WGResult": 69.96,
    "WGCountry": "East Germany",
    "WGAthlete": "Evelin Jahl-Schlaak",
    "MSResult": 66.38,
    "MSCountry": "Czechoslovakia",
    "MSAthlete": "Imrich Bugar",
    "WSResult": 65.06,
    "WSCountry": "Bulgaria",
    "WSAthlete": "Maria Petkova-Vergova",
    "MBResult": 66.32,
    "MBCountry": "Cuba",
    "MBAthlete": "Luis Delis",
    "WBResult": 67.4,
    "WBCountry": "USSR",
    "WBAthlete": "Tatyana Lesovaya"
  },
  {
    "Year": 1984,
    "MGResult": 66.6,
    "MGCountry": "West Germany",
    "MGAthlete": "Rolf Danneberg",
    "WGResult": 65.36,
    "WGCountry": "Netherlands",
    "WGAthlete": "Ria Stalman",
    "MSResult": 66.3,
    "MSCountry": "USA",
    "MSAthlete": "Mac Wilkins",
    "WSResult": 64.34,
    "WSCountry": "USA",
    "WSAthlete": "Leslie Deniz",
    "MBResult": 65.46,
    "MBCountry": "USA",
    "MBAthlete": "John Powell",
    "WBResult": 63.64,
    "WBCountry": "Romania",
    "WBAthlete": "Florenta Craciunescu"
  },
  {
    "Year": 1988,
    "MGResult": 68.82,
    "MGCountry": "East Germany",
    "MGAthlete": "Jurgen Schult",
    "WGResult": 72.3,
    "WGCountry": "East Germany",
    "WGAthlete": "Martina Hellmann",
    "MSResult": 67.48,
    "MSCountry": "URS",
    "MSAthlete": "Romas Ubartas",
    "WSResult": 69,
    "WSCountry": "East Germany",
    "WSAthlete": "Diana Gansky",
    "MBResult": 67.38,
    "MBCountry": "West Germany",
    "MBAthlete": "Rolf Danneberg",
    "WBResult": 69.74,
    "WBCountry": "Bulgaria",
    "WBAthlete": "Tsvetanka Khristova"
  },
  {
    "Year": 1992,
    "MGResult": 65.12,
    "MGCountry": "Lithuania",
    "MGAthlete": "Romas Ubartas",
    "WGResult": 70.06,
    "WGCountry": "Cuba",
    "WGAthlete": "Maritza Marten",
    "MSResult": 64.94,
    "MSCountry": "Germany",
    "MSAthlete": "Jurgen Schult",
    "WSResult": 67.3,
    "WSCountry": "Bulgaria",
    "WSAthlete": "Tsvetanka Khristova",
    "MBResult": 64.12,
    "MBCountry": "Cuba",
    "MBAthlete": "Roberto Moya",
    "WBResult": 66.24,
    "WBCountry": "Australia",
    "WBAthlete": "Daniela Costian"
  },
  {
    "Year": 1996,
    "MGResult": 69.4,
    "MGCountry": "Germany",
    "MGAthlete": "Lars Riedel",
    "WGResult": 69.66,
    "WGCountry": "Germany",
    "WGAthlete": "Ilke Wyludda",
    "MSResult": 66.6,
    "MSCountry": "Belarus",
    "MSAthlete": "Vladimir Dubrovshchik",
    "WSResult": 66.84,
    "WSCountry": "Russia",
    "WSAthlete": "Natalya Sadova",
    "MBResult": 65.8,
    "MBCountry": "Belarus",
    "MBAthlete": "Vasiliy Kaptyukh",
    "WBResult": 65.64,
    "WBCountry": "Belarus",
    "WBAthlete": "Elya Zvereva"
  },
  {
    "Year": 2000,
    "MGResult": 69.3,
    "MGCountry": "Lithuania",
    "MGAthlete": "Virgilijus Alekna",
    "WGResult": 68.4,
    "WGCountry": "Belarus",
    "WGAthlete": "Elya Zvereva",
    "MSResult": 68.5,
    "MSCountry": "Germany",
    "MSAthlete": "Lars Riedel",
    "WSResult": 69.96,
    "WSCountry": "Greece",
    "WSAthlete": "Anastasia Kelesidou",
    "MBResult": 68.19,
    "MBCountry": "South Africa",
    "MBAthlete": "Frantz Kruger",
    "WBResult": 65.2,
    "WBCountry": "Belarus",
    "WBAthlete": "Irina Yatchenko"
  },
  {
    "Year": 2004,
    "MGResult": 69.89,
    "MGCountry": "Lithuania",
    "MGAthlete": "Virgilijus Alekna",
    "WGResult": 67.02,
    "WGCountry": "Russia",
    "WGAthlete": "Natalya Sadova",
    "MSResult": 67.04,
    "MSCountry": "Hungary",
    "MSAthlete": "Zoltan Kovago",
    "WSResult": 67.9,
    "WSCountry": "Greece",
    "WSAthlete": "Anastasia Kelesidou",
    "MBResult": 66.66,
    "MBCountry": "Estonia",
    "MBAthlete": "Aleksander Tammert",
    "WBResult": 66.17,
    "WBCountry": "Belarus",
    "WBAthlete": "Irina Yatchenko"
  },
  {
    "Year": 2008,
    "MGResult": 68.82,
    "MGCountry": "Estonia",
    "MGAthlete": "Gerd Kanter",
    "WGResult": 64.74,
    "WGCountry": "USA",
    "WGAthlete": "Stephanie BrownTrafton",
    "MSResult": 67.82,
    "MSCountry": "Poland",
    "MSAthlete": "Piotr Malachowski",
    "WSResult": 63.64,
    "WSCountry": "Cuba",
    "WSAthlete": "Yarelys Barrios",
    "MBResult": 67.79,
    "MBCountry": "Lithuania",
    "MBAthlete": "Virgilijus Alekna",
    "WBResult": 62.59,
    "WBCountry": "Ukraine",
    "WBAthlete": "Olena Antonova"
  },
  {
    "Year": 2012,
    "MGResult": 68.27,
    "MGCountry": "Germany",
    "MGAthlete": "Robert Harting",
    "WGResult": 69.11,
    "WGCountry": "Crotia",
    "WGAthlete": "Sandra Perkovic",
    "MSResult": 68.18,
    "MSCountry": "Iran",
    "MSAthlete": "Ehsan Hadadi",
    "WSResult": 67.22,
    "WSCountry": "China",
    "WSAthlete": "Yanfeng Li",
    "MBResult": 68.03,
    "MBCountry": "Estonia",
    "MBAthlete": "Gerd Kanter",
    "WBResult": 66.38,
    "WBCountry": "Cuba",
    "WBAthlete": "Yarelys Barrios"
  }
];